### ISSUE TITLE
Ты ... сервелаты в xml обьявляешь если аннотации есть

### ISSUE THREAD

**Issue by itsmishakiva** [disabel1a/Lab-13-SUAI#1]

**Comment by disabel1a** [comment]
Чел, я эту хуйню в первый раз делал, думаешь я ебу как там все устроено?
Давай там не пукай! Я только учусь как никак.... Героям слава!



И я совместил описание в веб ихсемеле с аннотациями...



Хули ты вообще мой говно код палишь?!... Huh....?

чт, 16 нояб. 2023 г., 13:46 itsmishakiva ***@***.***>:

**Comment by disabel1a** [comment]
Да и откуда я мог это знать на тот момент?

**Comment by disabel1a** [comment]
Иди в пизду!

**Comment by disabel1a** [comment]
Ты - большой палец Ельцина!
